version: 2.1

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/buildpack-deps:stretch
      environment:
        TZ: /usr/share/zoneinfo/Asia/Tokyo

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: |
            sudo apt update
            sudo apt install \
              gcc-arm-none-eabi \
              fakeroot \
              libalgorithm-merge-perl \
              dpkg-dev \
              binutils-arm-none-eabi
              
      - run:
          command: |
            .circleci/build_linux.sh
            
      - run:
          command: |
            mkdir -p /tmp/build
            cp ./build/*.hex /tmp/build
            cp ./build/*.bin /tmp/build
            cp ./build/*.map /tmp/build
            cp ./build/*.elf /tmp/build
            ls /tmp/build

      - store_artifacts:
          path: /tmp/build/*

workflows:
  workflows:
    jobs:
      - build
